"""
Configuration constants for Research2Repo
Centralized constants to avoid hardcoded values
"""

# API and service endpoints
DEFAULT_OLLAMA_HOST = "http://127.0.0.1:11434"
DEFAULT_GROBID_URL = "http://127.0.0.1:8070/api/processFulltextDocument"

# Content truncation limits
MAX_ABSTRACT_LENGTH = 3000
MAX_CONTENT_DISPLAY_LENGTH = 5000
MAX_CONTENT_TRUNCATION_LENGTH = 3000

# Cache timeouts
MODEL_CACHE_TTL_SECONDS = 60
AVAILABLE_CACHE_TTL_SECONDS = 300

# Performance settings
DEFAULT_TIMEOUT_SECONDS = 120
DEFAULT_MAX_RETRIES = 3
DEFAULT_RETRY_DELAY_SECONDS = 5

# Coverage thresholds
DEFAULT_COVERAGE_THRESHOLD = 80
UNIT_TEST_COVERAGE_THRESHOLD = 85
INTEGRATION_TEST_COVERAGE_THRESHOLD = 75

# File size limits
MAX_PDF_SIZE_MB = 100
MAX_DOWNLOAD_SIZE_MB = 100

# Rate limiting
DEFAULT_REQUESTS_PER_MINUTE = 60
DEFAULT_TOKENS_PER_MINUTE = 32000

# Pipeline settings
DEFAULT_MAX_FIX_ITERATIONS = 2
DEFAULT_MAX_REFINE_ITERATIONS = 2
DEFAULT_MAX_DEBUG_ITERATIONS = 3

# Context settings
DEFAULT_CONTEXT_WINDOW = 100000
DEFAULT_CONTEXT_SUMMARY_INTERVAL = 5